# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/middleware/proto_build/message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n*tests/middleware/proto_build/message.proto"D\n\x18MessageWithCorrelationId\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t"/\n\x1bMessageWithoutCorrelationId\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\tb\x06proto3'  # noqa # pylint: disable=line-too-long
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tests.middleware.proto_build.message_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _MESSAGEWITHCORRELATIONID._serialized_start = 46  # noqa # pylint: disable=undefined-variable
    _MESSAGEWITHCORRELATIONID._serialized_end = 114  # noqa # pylint: disable=undefined-variable
    _MESSAGEWITHOUTCORRELATIONID._serialized_start = 116  # noqa # pylint: disable=undefined-variable
    _MESSAGEWITHOUTCORRELATIONID._serialized_end = 163  # noqa # pylint: disable=undefined-variable
# @@protoc_insertion_point(module_scope)
